import type { HardwareProfile } from "./types";

export const PROFILE_VERSION = 2;

function migrateProfile(profile: Partial<HardwareProfile>): HardwareProfile {
  const base = p({});
  return {
    ...base,
    ...profile,
    version: PROFILE_VERSION,
    createdAt: profile.createdAt || Date.now(),
    fullGpu: profile.fullGpu || profile.gpuRenderer || base.fullGpu,
    userAgent: profile.userAgent || base.userAgent,
    plugins: profile.plugins || [],
    mimeTypes: profile.mimeTypes || [],
    country: profile.country || inferCountry(profile.timezone || base.timezone),
    isMobile: profile.isMobile ?? (profile.touchPts ?? 0) > 0,
    availW: profile.availW ?? profile.screenW ?? base.availW,
    availH: profile.availH ?? (profile.screenH ?? base.screenH) - 40,
  };
}

function inferCountry(timezone: string): string {
  if (timezone.startsWith("America/")) return "US";
  if (timezone.startsWith("Europe/")) return "GB";
  if (timezone.startsWith("Asia/")) return "JP";
  if (timezone.startsWith("Australia/")) return "AU";
  if (timezone.startsWith("Africa/")) return "ZA";
  return "US";
}

function p(hw: Partial<HardwareProfile>): HardwareProfile {
  return {
    id: "",
    version: 2,
    createdAt: Date.now(),
    platform: "Win32",
    oscpu: "Windows NT 10.0; Win64; x64",
    userAgent:
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    gpuVendor: "Google Inc. (NVIDIA)",
    gpuRenderer:
      "ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Direct3D11 vs_5_0 ps_5_0, D3D11)",
    shortGpu: "NVIDIA GeForce RTX 3060",
    fullGpu: "ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Direct3D11 vs_5_0 ps_5_0)",
    cores: 8,
    memory: 16,
    screenW: 1920,
    screenH: 1080,
    availW: 1920,
    availH: 1040,
    dpr: 1.0,
    colorDepth: 24,
    touchPts: 0,
    isMobile: false,
    timezone: "America/New_York",
    language: "en-US",
    languages: ["en-US", "en"],
    city: "New York",
    country: "US",
    lat: 40.7128,
    lon: -74.006,
    connectionType: "ethernet",
    connectionEffective: "4g",
    downlink: 50,
    rtt: 15,
    battery: { charging: true, level: 0.85 },
    plugins: [],
    mimeTypes: [],
    clockSkew: 0,
    ...hw,
  };
}

export const PROFILES: HardwareProfile[] = [
  p({
    platform: "Win32",
    oscpu: "Windows NT 10.0; Win64; x64",
    gpuVendor: "Google Inc. (NVIDIA)",
    gpuRenderer:
      "ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Direct3D11 vs_5_0 ps_5_0, D3D11)",
    shortGpu: "NVIDIA GeForce RTX 3060",
    fullGpu: "ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Direct3D11 vs_5_0 ps_5_0)",
    cores: 8,
    memory: 16,
    screenW: 1920,
    screenH: 1080,
    availW: 1920,
    availH: 1040,
    dpr: 1.0,
    colorDepth: 24,
    touchPts: 0,
    isMobile: false,
    timezone: "America/New_York",
    language: "en-US",
    languages: ["en-US", "en"],
    city: "New York",
    country: "US",
    lat: 40.7128,
    lon: -74.006,
    connectionType: "ethernet",
    connectionEffective: "4g",
    downlink: 50,
    rtt: 15,
    battery: { charging: true, level: 0.85 },
  }),
  p({
    platform: "Win32",
    oscpu: "Windows NT 10.0; Win64; x64",
    gpuVendor: "Google Inc. (Intel)",
    gpuRenderer:
      "ANGLE (Intel, Mesa Intel(R) UHD Graphics (CML GT2), OpenGL 4.6)",
    shortGpu: "Intel UHD Graphics",
    fullGpu: "ANGLE (Intel, Mesa Intel(R) UHD Graphics (CML GT2), OpenGL 4.6)",
    cores: 4,
    memory: 8,
    screenW: 1366,
    screenH: 768,
    availW: 1366,
    availH: 728,
    dpr: 1.0,
    colorDepth: 24,
    touchPts: 0,
    isMobile: false,
    timezone: "America/Chicago",
    language: "en-US",
    languages: ["en-US", "en"],
    city: "Chicago",
    country: "US",
    lat: 41.8781,
    lon: -87.6298,
    connectionType: "wifi",
    connectionEffective: "4g",
    downlink: 25,
    rtt: 40,
    battery: { charging: false, level: 0.6 },
  }),
  p({
    platform: "Win32",
    oscpu: "Windows NT 10.0; Win64; x64",
    gpuVendor: "Google Inc. (NVIDIA)",
    gpuRenderer:
      "ANGLE (NVIDIA, NVIDIA GeForce RTX 4090 Direct3D11 vs_5_0 ps_5_0, D3D11)",
    shortGpu: "NVIDIA GeForce RTX 4090",
    fullGpu: "ANGLE (NVIDIA, NVIDIA GeForce RTX 4090 Direct3D11 vs_5_0 ps_5_0)",
    cores: 16,
    memory: 32,
    screenW: 2560,
    screenH: 1440,
    availW: 2560,
    availH: 1400,
    dpr: 1.0,
    colorDepth: 24,
    touchPts: 0,
    isMobile: false,
    timezone: "America/Los_Angeles",
    language: "en-US",
    languages: ["en-US", "en"],
    city: "Los Angeles",
    country: "US",
    lat: 34.0522,
    lon: -118.2437,
    connectionType: "ethernet",
    connectionEffective: "4g",
    downlink: 100,
    rtt: 8,
    battery: { charging: true, level: 0.95 },
  }),
  p({
    platform: "Win32",
    oscpu: "Windows NT 10.0; Win64; x64",
    gpuVendor: "Google Inc. (AMD)",
    gpuRenderer:
      "ANGLE (AMD, AMD Radeon RX 580 Series Direct3D11 vs_5_0 ps_5_0, D3D11)",
    shortGpu: "AMD Radeon RX 580",
    fullGpu: "ANGLE (AMD, AMD Radeon RX 580 Series Direct3D11 vs_5_0 ps_5_0)",
    cores: 4,
    memory: 8,
    screenW: 1440,
    screenH: 900,
    availW: 1440,
    availH: 860,
    dpr: 1.0,
    colorDepth: 24,
    touchPts: 0,
    isMobile: false,
    timezone: "America/Toronto",
    language: "en-CA",
    languages: ["en-CA", "en", "fr-CA", "fr"],
    city: "Toronto",
    country: "CA",
    lat: 43.6532,
    lon: -79.3832,
    connectionType: "wifi",
    connectionEffective: "4g",
    downlink: 30,
    rtt: 30,
    battery: { charging: false, level: 0.45 },
  }),
  p({
    platform: "MacIntel",
    oscpu: "Intel Mac OS X 10_15_7",
    gpuVendor: "Mozilla",
    gpuRenderer: "Apple M1",
    shortGpu: "Apple M1",
    fullGpu: "Apple M1",
    cores: 8,
    memory: 16,
    screenW: 2560,
    screenH: 1664,
    availW: 2560,
    availH: 1624,
    dpr: 2.0,
    colorDepth: 30,
    touchPts: 0,
    isMobile: false,
    timezone: "America/Los_Angeles",
    language: "en-US",
    languages: ["en-US", "en"],
    city: "San Francisco",
    country: "US",
    lat: 37.7749,
    lon: -122.4194,
    connectionType: "wifi",
    connectionEffective: "4g",
    downlink: 40,
    rtt: 20,
    battery: { charging: false, level: 0.75 },
  }),
  p({
    platform: "MacIntel",
    oscpu: "Intel Mac OS X 10_15_7",
    gpuVendor: "Mozilla",
    gpuRenderer: "AMD Radeon Pro 580X OpenGL Engine",
    shortGpu: "Radeon Pro 580X",
    fullGpu: "AMD Radeon Pro 580X OpenGL Engine",
    cores: 10,
    memory: 32,
    screenW: 5120,
    screenH: 2880,
    availW: 5120,
    availH: 2840,
    dpr: 2.0,
    colorDepth: 30,
    touchPts: 0,
    isMobile: false,
    timezone: "America/New_York",
    language: "en-US",
    languages: ["en-US", "en"],
    city: "New York",
    country: "US",
    lat: 40.7128,
    lon: -74.006,
    connectionType: "ethernet",
    connectionEffective: "4g",
    downlink: 80,
    rtt: 10,
    battery: { charging: true, level: 0.9 },
  }),
  p({
    platform: "MacIntel",
    oscpu: "Mac OS X 10_15_7",
    gpuVendor: "Mozilla",
    gpuRenderer: "Apple M2 Pro",
    shortGpu: "Apple M2 Pro",
    fullGpu: "Apple M2 Pro",
    cores: 12,
    memory: 16,
    screenW: 3024,
    screenH: 1964,
    availW: 3024,
    availH: 1924,
    dpr: 2.0,
    colorDepth: 30,
    touchPts: 0,
    isMobile: false,
    timezone: "Europe/London",
    language: "en-GB",
    languages: ["en-GB", "en"],
    city: "London",
    country: "GB",
    lat: 51.5074,
    lon: -0.1278,
    connectionType: "wifi",
    connectionEffective: "4g",
    downlink: 35,
    rtt: 25,
    battery: { charging: true, level: 0.8 },
  }),
  p({
    platform: "Linux x86_64",
    oscpu: "Linux x86_64",
    gpuVendor: "Mozilla",
    gpuRenderer: "Mesa Intel(R) UHD Graphics 630 (CFL GT2)",
    shortGpu: "Intel UHD Graphics 630",
    fullGpu: "Mesa Intel(R) UHD Graphics 630 (CFL GT2)",
    cores: 8,
    memory: 16,
    screenW: 1920,
    screenH: 1080,
    availW: 1920,
    availH: 1040,
    dpr: 1.0,
    colorDepth: 24,
    touchPts: 0,
    isMobile: false,
    timezone: "Europe/Berlin",
    language: "de-DE",
    languages: ["de-DE", "de"],
    city: "Berlin",
    country: "DE",
    lat: 52.52,
    lon: 13.405,
    connectionType: "ethernet",
    connectionEffective: "4g",
    downlink: 45,
    rtt: 18,
    battery: { charging: true, level: 0.7 },
  }),
  p({
    platform: "Linux x86_64",
    oscpu: "Linux x86_64",
    gpuVendor: "Mozilla",
    gpuRenderer: "AMD Radeon Graphics (radeonsi, raphael, ACO, DRM 3.54)",
    shortGpu: "AMD Radeon Graphics",
    fullGpu: "AMD Radeon Graphics (radeonsi, raphael, ACO, DRM 3.54)",
    cores: 12,
    memory: 32,
    screenW: 1920,
    screenH: 1080,
    availW: 1920,
    availH: 1040,
    dpr: 1.0,
    colorDepth: 24,
    touchPts: 0,
    isMobile: false,
    timezone: "Europe/Amsterdam",
    language: "nl-NL",
    languages: ["nl-NL", "nl"],
    city: "Amsterdam",
    country: "NL",
    lat: 52.3676,
    lon: 4.9041,
    connectionType: "wifi",
    connectionEffective: "4g",
    downlink: 55,
    rtt: 12,
    battery: { charging: false, level: 0.55 },
  }),
  p({
    platform: "Win32",
    oscpu: "Windows NT 10.0; Win64; x64",
    gpuVendor: "Google Inc. (Intel)",
    gpuRenderer:
      "ANGLE (Intel, Mesa Intel(R) Iris(R) Xe Graphics (TGL GT2), OpenGL 4.6)",
    shortGpu: "Intel Iris Xe Graphics",
    fullGpu:
      "ANGLE (Intel, Mesa Intel(R) Iris(R) Xe Graphics (TGL GT2), OpenGL 4.6)",
    cores: 8,
    memory: 16,
    screenW: 1920,
    screenH: 1080,
    availW: 1920,
    availH: 1040,
    dpr: 1.5,
    colorDepth: 24,
    touchPts: 10,
    isMobile: false,
    timezone: "Asia/Tokyo",
    language: "ja-JP",
    languages: ["ja-JP", "ja"],
    city: "Tokyo",
    country: "JP",
    lat: 35.6762,
    lon: 139.6503,
    connectionType: "wifi",
    connectionEffective: "4g",
    downlink: 20,
    rtt: 45,
    battery: { charging: false, level: 0.65 },
  }),
  p({
    platform: "MacIntel",
    oscpu: "Intel Mac OS X 10_15_7",
    gpuVendor: "Mozilla",
    gpuRenderer: "Mesa Intel(R) Iris(R) Plus Graphics (ICL GT2)",
    shortGpu: "Intel Iris Plus Graphics",
    fullGpu: "Mesa Intel(R) Iris(R) Plus Graphics (ICL GT2)",
    cores: 6,
    memory: 16,
    screenW: 2560,
    screenH: 1600,
    availW: 2560,
    availH: 1560,
    dpr: 2.0,
    colorDepth: 30,
    touchPts: 0,
    isMobile: false,
    timezone: "Europe/Paris",
    language: "fr-FR",
    languages: ["fr-FR", "fr"],
    city: "Paris",
    country: "FR",
    lat: 48.8566,
    lon: 2.3522,
    connectionType: "wifi",
    connectionEffective: "4g",
    downlink: 35,
    rtt: 22,
    battery: { charging: false, level: 0.5 },
  }),
  p({
    platform: "Win32",
    oscpu: "Windows NT 10.0; Win64; x64",
    gpuVendor: "Google Inc. (NVIDIA)",
    gpuRenderer:
      "ANGLE (NVIDIA, NVIDIA GeForce RTX 4060 Laptop GPU Direct3D11 vs_5_0 ps_5_0, D3D11)",
    shortGpu: "NVIDIA GeForce RTX 4060",
    fullGpu:
      "ANGLE (NVIDIA, NVIDIA GeForce RTX 4060 Laptop GPU Direct3D11 vs_5_0 ps_5_0)",
    cores: 8,
    memory: 16,
    screenW: 1920,
    screenH: 1080,
    availW: 1920,
    availH: 1040,
    dpr: 1.25,
    colorDepth: 24,
    touchPts: 0,
    isMobile: false,
    timezone: "Australia/Sydney",
    language: "en-AU",
    languages: ["en-AU", "en"],
    city: "Sydney",
    country: "AU",
    lat: -33.8688,
    lon: 151.2093,
    connectionType: "wifi",
    connectionEffective: "4g",
    downlink: 30,
    rtt: 35,
    battery: { charging: false, level: 0.7 },
  }),
  p({
    platform: "Linux x86_64",
    oscpu: "Linux x86_64",
    gpuVendor: "Mozilla",
    gpuRenderer: "NVIDIA GeForce GTX 1660/PCIe/SSE2",
    shortGpu: "NVIDIA GeForce GTX 1660",
    fullGpu: "NVIDIA GeForce GTX 1660/PCIe/SSE2",
    cores: 6,
    memory: 16,
    screenW: 1920,
    screenH: 1080,
    availW: 1920,
    availH: 1040,
    dpr: 1.0,
    colorDepth: 24,
    touchPts: 0,
    isMobile: false,
    timezone: "Asia/Dubai",
    language: "ar-AE",
    languages: ["ar-AE", "ar"],
    city: "Dubai",
    country: "AE",
    lat: 25.2048,
    lon: 55.2708,
    connectionType: "ethernet",
    connectionEffective: "4g",
    downlink: 60,
    rtt: 15,
    battery: { charging: true, level: 0.9 },
  }),
];

export function pickRandomProfile(): HardwareProfile {
  const base = PROFILES[Math.floor(Math.random() * PROFILES.length)]!;
  return {
    ...base,
    id: Date.now().toString(36) + Math.random().toString(36).slice(2, 8),
    version: 2,
    createdAt: Date.now(),
    clockSkew: (Math.random() - 0.5) * 2000,
    battery: {
      ...base.battery,
      level: clampBattery(base.battery.level + (Math.random() - 0.5) * 0.1),
    },
  };
}

export function deriveProfile(
  profile: HardwareProfile,
  origin: string,
): HardwareProfile {
  const baseId = profile.id || "base";
  const seed = hashOrigin(baseId, origin);
  const noise = new SeededRNG(seed);

  const derivedId = baseId + ":" + seed.toString(36);

  return {
    ...profile,
    id: derivedId,
    cores: noise.int(profile.cores - 1, profile.cores + 1),
    screenW: noise.int(profile.screenW - 4, profile.screenW + 4),
    screenH: noise.int(profile.screenH - 4, profile.screenH + 4),
    lat: profile.lat + noise.float(-0.005, 0.005),
    lon: profile.lon + noise.float(-0.005, 0.005),
    downlink: noise.int(profile.downlink - 5, profile.downlink + 5),
    rtt: noise.int(profile.rtt - 5, profile.rtt + 5),
    battery: {
      ...profile.battery,
      level: clampBattery(profile.battery.level + noise.float(-0.03, 0.03)),
    },
  };
}

class SeededRNG {
  private state: number;
  constructor(seed: number) {
    this.state = seed;
  }
  next(): number {
    this.state ^= this.state << 13;
    this.state ^= this.state >>> 17;
    this.state ^= this.state << 5;
    return (this.state >>> 0) / 0xffffffff;
  }
  int(min: number, max: number): number {
    return Math.floor(min + this.next() * (max - min + 1));
  }
  float(min: number, max: number): number {
    return min + this.next() * (max - min);
  }
}

function hashOrigin(id: string, origin: string): number {
  const str = `${id}:${origin}`;
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    hash = (hash << 5) - hash + str.charCodeAt(i);
    hash |= 0;
  }
  return hash >>> 0;
}

function clampBattery(val: number): number {
  return Math.max(0.05, Math.min(1, val));
}

export { migrateProfile };
